# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Export-Attrs
version:      0.0.3
version_from: lib/Perl6/Export/Attrs.pm
installdirs:  site
requires:
    Attribute::Handlers:           0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
