---
abstract: "The Perl 6 'is export(...)' trait as a Perl 5 attribute"
author:
  - 'Damian Conway <DCONWAY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl6-Export-Attrs
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: '0'
  PadWalker: '0'
  Test::More: '0'
  version: '0'
version: '0.000005'
